### ISSUE TITLE
Could add cube list into virtual walls?

### ISSUE THREAD

**Issue by kc944201** [Kasidit0052/ROS-Naviz#1]
Hi, 

Are there any methods that could add the markers(cube list) with the virtual wall?

Thank you for your contribution!

**Comment by kc944201** [comment]
I got the following problems while opening the client, and the web app is black.
how to solve it? Thank you
![image](https://user-images.githubusercontent.com/57080316/124899257-84fae380-e012-11eb-867d-82804a25e95a.png)
![image](https://user-images.githubusercontent.com/57080316/124899368-a065ee80-e012-11eb-9da5-ff1d89e67bed.png)

**Comment by Kasidit0052** [comment]
@kc944201 Thank you for visiting our repository. I highly doubt that it is the communication error. You can modify the **ros_server/robot-app/src/Components/MyImage.js** `var localhost`  and **ros_server/robot-app/src/Components/MapSection.js** `const ENDPOINT` **url** respectively. This solution probably solves your problem.

**Comment by Kasidit0052** [comment]
Unfortunately for the markers, it is beyond our capability. However, you can look at **roslibjs** and **ros2djs** doc for more insight about how to implement them.

**Comment by kc944201** [comment]
@Kasidit0052 Thank your answers.
I already modified the two files you say, I change the URL to 192.168.0.109
![image](https://user-images.githubusercontent.com/57080316/125037078-4de60a00-e0c6-11eb-93cd-15d6d5dd92e0.png)

the terminal had appeared text was 'a user connected'.
![image](https://user-images.githubusercontent.com/57080316/125037326-9271a580-e0c6-11eb-9c8c-065d63baf376.png)

But the react app web is still black.

**Comment by Kasidit0052** [comment]
This might be the problem on server-side. You should modify the **ros_server/scripts/server.js** `ros.connect("ws://192.168.1.16:9090")` with new url.

**Comment by kc944201** [comment]
@Kasidit0052 It works now!!! Thank you for helping.

However, I had a problem with the map's scale size.
when I using a real robot with navigation, I found the map is not right on react app.
I can't see the whole map and can't swipe or spin the map with a mouse.

as in the following picture, you can see the map between Rviz and React app is not the same scale and position, a part of the map was disappear on the app.
![Screenshot](https://user-images.githubusercontent.com/57080316/125064642-6b759c80-e0e3-11eb-8d13-9d3ea267ea95.png)

another problem is the map index at the ros_server/scripts/ROS_CV_HELPER.js: 47
occupancyGridMat.set(col, row, [val, val, val]);
Mat::Set - index out of bounds: mat::at row at index 576

**Comment by kc944201** [comment]
@Kasidit0052 Could you please help me to resolve the above issues? 
I really need your helping to complete my project.
Thank you!

**Comment by Kasidit0052** [comment]
@kc944201 Unfortunately this project is far from perfect. If you setup map configuration different from Turtlebot ones, the transformation might break in some scenario. We haven't solved a responsive map and shift feature yet.

**Comment by Kasidit0052** [comment]
@kc944201

**Comment by Kasidit0052** [comment]
@kc944201 Currently, this project is not maintained. You need to solve some transformation problem to satisfy your requirements.

**Comment by kc944201** [comment]
I got it. Thank you!

**Comment by funnyrabbitvu** [comment]
Hi guys, 
I got same issue here. No map displayed and I ran every ros nodes (gazebo, rviz navigation) on my system for sure. And I'm pretty sure that I changed my localhost both in MyImage.js, MapSection.js and server.js files into my local IP address but the map window still in black, I didn't know why.
Please help me, sir.
Thank you alot!
@kc944201 
@Kasidit0052 

![image](https://user-images.githubusercontent.com/48290085/127760001-dfe51746-eff1-430e-ba71-759bfb9cb7cf.png)

**Comment by funnyrabbitvu** [comment]
My connections have been established completely through rosbridge server, sir.

![image](https://user-images.githubusercontent.com/48290085/127760066-df6ca909-4a28-4f30-91c8-166f494fa35f.png)

**Comment by kc944201** [comment]
Actually, I can't help you because I used another repo. and I got a good experience
I'm not sure could I post the other repo. in here.

**Comment by funnyrabbitvu** [comment]
![image](https://user-images.githubusercontent.com/48290085/127760151-3a5bedb0-8b10-494e-bcaf-74ac62a9b9b2.png)

Did I miss something here?
I use his repo to run these demo, with all these requirements.
Could you please share your working on repo, sir? I will help me alot so thankful for that!

**Comment by funnyrabbitvu** [comment]
@kc944201 
Did I miss something here?
I use his repo to run these demo, with all these requirements.
Could you please share your working on repo, sir? I will help me alot so thankful for that!

![image](https://user-images.githubusercontent.com/48290085/127760224-c39685d3-8511-4af2-bd2e-866f6949f810.png)

**Comment by kc944201** [comment]
@funnyrabbitvu If you need the virtual wall package.
I will recommend DylanLN/virtual_wall, it's easy to set up.

**Comment by funnyrabbitvu** [comment]
@kc944201 
Thank you pretty much, sir. I will try to figure it out.

**Comment by funnyrabbitvu** [comment]
@kc944201 
Could I see your launch virtual wall file content, sir?
I think my problem is here in virtual_wall_server, there is nothing...

![image](https://user-images.githubusercontent.com/48290085/127760514-2edd8111-6c69-45db-80c3-6a77fce7e4a5.png)

**Comment by kc944201** [comment]
As I said I already changed another repo., so I'm sorry I can't help you in here.

**Comment by funnyrabbitvu** [comment]
@kc944201 
Have a nice day sir.
I am here with new issue that the laser scan visualization but wrong tf.
Did you ever face to this problem before? I created a tfClient with fixed frame /odom that subscribes from /base_scan frame of the Turtlebot3.
Hope to receive replying from you. Thank you alot, sir.

![Screenshot from 2021-08-27 03-27-45](https://user-images.githubusercontent.com/48290085/131473549-0e43ed4e-5310-4395-a117-84861228133a.png)
